### ISSUE TITLE
is there an example for client?

### ISSUE THREAD

**Issue by kant777** [robaho/lrmp#1]
I see an example for server https://github.com/robaho/lrmp/blob/master/examples/lrmptest.go but is there an example for client? I tried command line tools like `nc` and `socat` but none of them received any data after starting the server and inputting some message via STDIN

```
nc -u 225.0.0.100 6000
socat - UDP:225.0.0.100:6000
```

**Comment by robaho** [comment]
There is no client/server - it is peer to peer.

You can run two instances and type a message in one and you will see the message in the other - just make sure both are configured for the same udp host & port.

It uses multicast traffic so you need to configure the packet capture to join the group.

**Comment by kant777** [comment]
Got it. is there a way to do one to many multicast? for example the one is the server and the many are the peers that want to listen for notifications. Also if one the peers send some message I dont want it to be broadcasted to other peers. so in my case it has to be all one way meaning from the server I want to send notifications to bunch of clients/receivers/peers in a multicast fashion

**Comment by robaho** [comment]
You would need to write that layer. You might want to look at a message bus - like Nats.IO or ZeroMQ. 

Typically you would use a broadcast channel and directed connections from the peers back to the server.

**Comment by kant777** [comment]
But then I am back to TCP right? I am trying to use multicast as you suggested in the email thread for strict latency requirements.

**Comment by robaho** [comment]
Well, you only use tcp from the peer back to the server. If you expect each peer when they receive the message to send a message back to server - then use you need 20k tcp connections and the server needs to process 20k messages every 5 ms - not going to happen. 

You need to use multicast both ways. The peers should ignore messages sent to the server - ie. that “group” is written to by peers and read by the server. 

A bus like Nats makes this simple. I am not sure if Nats supports UDP though.

**Comment by robaho** [comment]
Btw, reading the spec contains the answers to your questions: https://github.com/robaho/lrmp/blob/master/doc/draft-liao-lrmp-00.txt
